Description: Certificates used by Cognito

Parameters:
  TargetEnvironment:
    Description: 'Examples are local, dev, test, prod, etc'
    Type: 'String'
    
  ProductName:
    Description: 'Represents the name of the product you want to call the deployment'
    Type: 'String'

Conditions: 
  CreateProdResources: !Equals [ !Ref TargetEnvironment, prod ]
  
Resources:
  CertificateAuthDomain:
    Type: AWS::CertificateManager::Certificate
    Properties:
        DomainName: !If [CreateProdResources, !Sub "auth.${ProductName}.app", !Sub "${TargetEnvironment}-auth.${ProductName}.app"]
        DomainValidationOptions:
          - DomainName:  !If [CreateProdResources, !Sub "auth.${ProductName}.app", !Sub "${TargetEnvironment}-auth.${ProductName}.app"]
            HostedZoneId:  {'Fn::ImportValue': !Sub '${ProductName}-route53-dotAppZone'}
        ValidationMethod: DNS
        #SubjectAlternativeNames:
        #    - !If [CreateProdResources, !Sub "auth.${ProductName}app.com", !Sub "${TargetEnvironment}-auth.${ProductName}app.com"]
        Tags:
          - Key: environment
            Value: !Ref TargetEnvironment
          - Key: orchestration
            Value: cloud-formation
          - Key: service
            Value: auth
          - Key: service-type
            Value: aws-managed
          - Key: product
            Value: !Ref ProductName
          
Outputs:
  CertificateAuthDomain:
    Description: 'ARN of the Certificate created for auth with Cognito'
    Value: !Ref CertificateAuthDomain
    Export:
      Name: !Sub '${ProductName}-${TargetEnvironment}-certificate-auth'